export { default as authRoutes } from "./authRoutes";
export { default as vehicleBrandRoutes } from "./vehicleBrandRoutes";
export { default as vehiclesRoutes } from "./vehiclesRoutes";
export { default as carrierRoutes } from "./carrierRoutes";
export { default as zoneRoutes } from "./zoneRoutes";
export { default as cropRoutes } from "./cropRoutes";
export { default as zoneTripPriceRoute } from "./zoneTripPriceRoutes";
export { default as placeRoutes } from "./placeRoutes";
export { default as tripRoutes } from "./tripRoutes";